AJDesign/Controllers/AdministradorController.cs
using Entidades;
using Entidades.Views;
using Servicios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AJDesign.Controllers
{
    public class AdministradorController : Controller
    {
        ServicioAdministrador servicioAdministrador;

        public AdministradorController()
        {
            AJDESIGNEntities context = new AJDESIGNEntities();
            servicioAdministrador = new ServicioAdministrador(context);
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(VMLogin vmlogin)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }
                else
                {
                    Boolean a = servicioAdministrador.ValidarDatos(vmlogin);
                    if (a == true)
                    {
                        return RedirectToAction("Precio", "Precios");
                    }
                    else
                    {
                        //return RedirectToAction("Index","Home");
                        TempData["Mensaje"] = "Email o password incorrecto";
                        return View();
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error: ", ex.Message);
            }
            return RedirectToAction("Precio", "Precios");
        }

        // GET: Administrador
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AgregarDisenio()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AgregarDisenio(VMAgregarDisenios agregardisenio)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }
                else
                {
                    servicioAdministrador.AgregarDisenio(agregardisenio);
                }
            }catch (Exception ex)
            {
                ModelState.AddModelError("Error: ", ex.Message);
            }
            return RedirectToAction("Precio", "Precios");
        }

        [HttpGet]
        public ActionResult ModificarDisenio(int idDisenios)
        {
            VMModificarDisenio vm = new VMModificarDisenio();
            vm.IdDisenios = idDisenios;
            return View(vm);
        }
       
        [HttpPost]
        public ActionResult ModificarDisenio(VMModificarDisenio p)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(p);
                }
                else
                {
                    servicioAdministrador.actualizarPrecio(p);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error: ", ex.Message);
            }
            return RedirectToAction("Precio", "Precios"); 
        }


        [HttpGet]
        public ActionResult Eliminar(int idDisenios)
        {
            servicioAdministrador.Eliminar(idDisenios);
            return RedirectToAction("Precio", "Precios");
        }

    }
}

AJDesign/Controllers/HomeController.cs
using Entidades;
using Entidades.Enum;
using Entidades.Views;
using Servicios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AJDesign.Controllers
{
    public class HomeController : Controller
    {
        ServicioHome servicioHome;
        public HomeController()
        {
            AJDESIGNEntities context = new AJDESIGNEntities();
            servicioHome = new ServicioHome(context);
        }
        public ActionResult Index()
        {
            return View();
        }
    }
}

AJDesign/Controllers/PreciosController.cs
using Entidades;
using Servicios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AJDesign.Controllers
{
    public class PreciosController : Controller
    {
        ServicioPrecios serviciosPrecios;

        public PreciosController()
        {
            AJDESIGNEntities context = new AJDESIGNEntities();
            serviciosPrecios = new ServicioPrecios(context);
        }

        [HttpGet]
        public ActionResult Precio()
        {
          List<Disenios> listaPrecio = serviciosPrecios.TraerListaDePrecios();
          return View("Precio",listaPrecio);
        }

    }
}

AJDesign/Views/Administrador/AgregarDisenio.cshtml
@model Entidades.Disenios
@{
    ViewBag.Title = "AgregarDisenio";
}
<center>
    <h2>Agregar Diseño</h2><br />

    @using (Html.BeginForm("AgregarDisenio", "Administrador", FormMethod.Post, new { @class = "login100-form validate-form p-b-33 p-t-5" }))
    {
        <div class="wrap-input100 validate-input">
            @*Inputs con razor*@
            Nombre:@Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "input100" } })
            <span class="focus-input100"></span>
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
        <br />

        <div class="wrap-input100 validate-input">
            @*Inputs con razor*@
            Precio:  @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "input100" } })
            <span class="focus-input100"></span>
            @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
        </div>
        <br />

        <button type="submit">Agregar diseño</button>
    }
</center>

AJDesign/Views/Administrador/Login.cshtml
@model Entidades.Views.VMLogin
@{
    ViewBag.Title = "Login";
}
@{
    var Mensaje = ""; //creo var mensaje vacia

    if (TempData["Mensaje"] != null) //Si TempData no esta vacio, a la variable mensaje le asigno el valor de tempdata (Gracias por su donación)
    {
        Mensaje = TempData["Mensaje"].ToString();
    }

    if (Mensaje == "Email o password incorrecto") //Si mensaje es igual al mismo texto que puse en el controller (TempData["Mensaje"] = "Gracias por su donación") pongo el siguiente texto
    {
        <center><h2 class="p-3 mb-2 bg-success"><i>¡Email o password incorrecto!</i></h2></center>
    }
    <br>
    <br>
}
<center>
    <h2>Solo podrás iniciar sesión si sos administrador</br></h2>

    @using (Html.BeginForm("Login", "Administrador", FormMethod.Post, new { @class = "login100-form validate-form p-b-33 p-t-5" }))
    {

        <div class="wrap-input100 validate-input">
            @*Inputs con razor*@
            Email  @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "input100" } })
            <span class="focus-input100"></span>
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div><br />

        <div class="wrap-input100 validate-input">
            @*Inputs con razor*@
            Password @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "input100" }, Type = "password" })
            <span class="focus-input100"></span>
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div><br />

        <button type="submit">Iniciar sesión</button>
    }
</center>

AJDesign/Views/Administrador/ModificarDisenio.cshtml
@model Entidades.Views.VMModificarDisenio
@{
    ViewBag.Title = "ModificarPrecio";
}
<center>
    <h2>ModificarPrecio</h2>

    @using (Html.BeginForm("ModificarDisenio", "Administrador", FormMethod.Post, new { @class = "login100-form validate-form p-b-33 p-t-5" }))
    {
        <input type="hidden" name="idDisenios" value=@Model.IdDisenios />

        <div class="wrap-input100 validate-input">
            @*Inputs con razor*@
            Nombre: @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "input100" } })
            <span class="focus-input100"></span>
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div><br />

        <div class="wrap-input100 validate-input">
            @*Inputs con razor*@
            Precio: @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "input100" } })
            <span class="focus-input100"></span>
            @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
        </div>
        <br />


        <button type="submit">Modificar</button>
    }
</center>

AJDesign/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home |";
}


<!DOCTYPE HTML>
<html>

<head>
    <title>AJDesign</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link href="~/Content/Css/main.css" rel="stylesheet" />

</head>
<body class="is-preload">

    <!-- Header -->
    <header id="header">
        <div class="inner">
            <center><a class="image avatar"><img src="~/Content/img/ajdesign.png" /></a></center>
            <center>
                <h1>
                    <div class="icon brands fa-whatsapp"> 11 3084-3934</div>
                </h1>
            </center>
        </div>
    </header>

    <!-- Main -->
    <div id="main">

        <!-- One -->
        <section id="one">
            <header class="major">
                @{
                    var Mensaje = "";

                    if (TempData["Mensaje"] != null)
                    {
                        Mensaje = TempData["Mensaje"].ToString();
                    }

                    if (Mensaje == "Bienvenidx")
                    {
                        <center><h2 class="alert alert-success"><i>Bienvenidx a AJDesign</i></h2></center>
                    }<br>
                }
                <h2>
                    <center><i><b><u>AJDESIGN</u></b></i></center>
                </h2>
            </header>
            <p>
                <h4>
                    ♥ AJDESIGN surge como un emprendimiento FAMILIAR?, con el único objetivo de poder brindarle
                    a nuestros clientes diseños de buena calidad y brindarles la posibilidad de poder tener marca
                    propia en sus emprendimientos. <br />

                    El cliente puede bocetar en un papel lo que imagina y nosotros lo plasmamos y lo hacemos realidad.
                    Contamos con precios muy accesibles y trabajamos con el 50% de la seña. Para darle mas tranquilidad
                    y seguridad a nuestros clientes a medida que se va realizando el diseño se va pasando como va quedando
                    por si el cliente desea modificar algo del diseño. El Cliente tiene 3 modificaciones SIN COSTO para
                    modificar TODO lo que desee. A partir de la cuarta modificación tiene un recargo de $100 donde tambien
                    podra modificar TODO lo que desee.
                </h4>
            </p>
        </section>

        <!-- Two -->
        <section id="two">
            <center><h1><i><b>Galería de trabajos</b></i></h1></center>
            <div class="row">
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/a.jpg" class="image fit thumb"><img src="~/Content/img/fulls/a.jpg" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/b.jpg" class="image fit thumb"<img src="~/Content/img/thumbs/b.jpg" />></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/c.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/c.jpg" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/d.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/d.jpg" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/e.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/e.jpg" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/f.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/f.jpg" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/g.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/g.jpg" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/h.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/h.jpg" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/i.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/i.jpg" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/j.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/j.jpg" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/k.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/k.jpg" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/l.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/l.jpg" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/m.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/m.jpg" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/n.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/n.jpg" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/o.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/o.jpg" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/p.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/p.jpg" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/q.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/q.jpg" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/r.png" class="image fit thumb"><img src="~/Content/img/thumbs/r.png" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/s.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/s.jpg" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/t.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/t.jpg" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/u.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/u.jpg" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/v.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/v.jpg" alt="" /></a>
                </article>
                <article class="col-6 col-12-xsmall work-item">
                    <a href="~/Content/img/fulls/w.jpg" class="image fit thumb"><img src="~/Content/img/thumbs/w.jpg" alt="" /></a>
                </article>
            </div>
        </section>



        <!-- Footer -->
        <footer id="footer">
            <div class="inner">
                <center>
                    <ul class="icons">
                        <li><a href="https://www.instagram.com/ajdesign.ok/?hl=es-la" target="_blank" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
                        <li><a href="https://www.facebook.com/a.a.12.96" target="_blank" class="icon brands fa-facebook"><span class="label">Dribbble</span></a></li>
                        <li><a href="mailto:ajdesign.a.a@outlook.com" class="icon solid fa-envelope"><span class="label">Email</span></a></li>
                    </ul>


                    <ul class="copyright">
                        <li>&copy; @DateTime.Now.Year</li>
                        <li>AJDesign</li>
                    </ul>
                </center>
            </div>
        </footer>

        <!-- Scripts -->
        <script src="~/Content/js/jquery.min.js"></script>
        <script src="~/Content/js/jquery.poptrox.min.js"></script>
        <script src="~/Content/js/browser.min.js"></script>
        <script src="~/Content/js/breakpoints.min.js"></script>
        <script src="~/Content/js/util.js"></script>
        <script src="~/Content/js/main.js"></script>

</body>
</html>

AJDesign/Views/Home/Login.cshtml
@model Entidades.Views.VMLogin
@{
    ViewBag.Title = "Login";

    string mensajeAdvertencia;

    if (Request["mensaje"] != null)
    {
        mensajeAdvertencia = Request["mensaje"];
    }
    else
    {
        mensajeAdvertencia = (string)ViewData["mensajeAdvertencia"];
    }

    string mensajeError = (string)ViewData["mensajeError"];
    string mensajeErrorC = (string)ViewData["mensajeErrorC"];
    string mensajeCorrecto = (string)ViewData["mensajeCorrecto"];
}

<h2>Login</h2>

@using (Html.BeginForm("Login", "Home", FormMethod.Post, new { @class = "login100-form validate-form p-b-33 p-t-5" }))
{
    @Html.AntiForgeryToken()

    if (mensajeError != null)
    {
        <div class="p-3 mb-2 bg-danger text-white">@mensajeError</div>
    }
    if (mensajeErrorC != null)
    {
        <div class="p-3 mb-2 bg-danger text-white">@mensajeError</div>
    }
    if (mensajeAdvertencia != null)
    {
        <div class="p-3 mb-2 bg-warning text-white">@mensajeAdvertencia</div>
    }
    if (mensajeCorrecto != null)
    {
        <div class="p-3 mb-2 bg-success text-white">@mensajeCorrecto</div>
    }

    var Mensaje = "";

    if (TempData["Mensaje"] != null)
    {
        Mensaje = TempData["Mensaje"].ToString();
    }

    if (Mensaje == "Login")
    {
        <center><h2 class="alert alert-success"><i>Ingrese sesión</i></h2></center>
    }
    <br>

    <center>
        <div class="breadcrumb">
            <div class="wrap-input100 validate-input">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "btn btn-default", placeholder = Html.DisplayNameFor(x => x.Email) } })
                <span class="focus-input100" data-placeholder="&#xe813;"></span>
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div><br>

            <div class="wrap-input100 validate-input">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "btn btn-default", placeholder = Html.DisplayNameFor(x => x.Password), Type = "Password" } })
                <span class="focus-input100" data-placeholder="&#xe813;"></span>
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div><br>

            <button type="submit" class="btn btn-info">Login</button>
        </div>
    </center>
}

AJDesign/Views/Home/Registro.cshtml
@model Entidades.Views.VMRegistro
@{
    ViewBag.Title = "Registro";
    string mensajeAdvertencia = (string)ViewData["mensajeAdvertencia"];
    string mensajeError = (string)ViewData["mensajeError"];

}

<center><h1><i><b>Registro</></b></i></h1><br /></center>

@using (Html.BeginForm("Registro", "Home", FormMethod.Post, new { @class = "login100-form validate-form p-b-33 p-t-5" }))
{
    @Html.AntiForgeryToken()

    if (mensajeError != null)
    {
        <div class="p-3 mb-2 bg-danger text-white">@mensajeError</div>
    }
    if (mensajeAdvertencia != null)
    {
        <div class="p-3 mb-2 bg-warning text-white">@mensajeAdvertencia</div>
    }
    <center>
        <div class="breadcrumb">
            <div class="wrap-input100 validate-input">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "btn btn-default", placeholder = Html.DisplayNameFor(x => x.Nombre) } })
                <span class="focus-input100" data-placeholder="&#xe813;"></span>
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div><br>

            <div class="wrap-input100 validate-input">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "btn btn-default", placeholder = Html.DisplayNameFor(x => x.Apellido) } })
                <span class="focus-input100" data-placeholder="&#xe813;"></span>
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div><br>

            <div class="wrap-input100 validate-input">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "btn btn-default", placeholder = Html.DisplayNameFor(x => x.Email) } })
                <span class="focus-input100" data-placeholder="&#xe813;"></span>
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div><br>

            <div class="wrap-input100 validate-input">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "btn btn-default", placeholder = Html.DisplayNameFor(x => x.Password), Type = "Password" } })
                <span class="focus-input100" data-placeholder="&#xe813;"></span>
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div><br>

            <div class="wrap-input100 validate-input">
                @Html.EditorFor(model => model.Password2, new { htmlAttributes = new { @class = "btn btn-default", placeholder = Html.DisplayNameFor(x => x.Password2), Type = "Password" } })
                <span class="focus-input100" data-placeholder="&#xe813;"></span>
                @Html.ValidationMessageFor(model => model.Password2, "", new { @class = "text-danger" })
            </div><br><br>

            <button type="submit" class="btn btn-info">Registrarse</button><br />
        </div>
    </center>
}

AJDesign/Views/Precios/Precio.cshtml
@model List<Entidades.Disenios>
@{
    ViewBag.Title = "Precios |";
}
<link href="~/Content/Css/Footer.css" rel="stylesheet" />

<center><i><b>Lista de precios</b></i></center>
<table class="table">
    <thead>
        <tr>
            <th scope="col"><h3>Diseños</h3></th>
            <th scope="col"><h3>Precios</h3></th>
            <th scope="col"><h3>Actualizar precio</h3></th>
            <th scope="col"><h3>Eliminar diseño</h3></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <th scope="col" class="text-danger">
                @item.Nombre<br />
            </th>
            <th scope="col" class="text-danger">
                @item.Precio
            </th>

            @using (Html.BeginForm("ModificarDisenio", "Administrador", FormMethod.Get, new { @class = "login100-form validate-form p-b-33 p-t-5" }))
            {
                <th scope="col" class="text-danger">
                    <a href="~/Administrador/ModificarDisenio?idDisenios=@item.IdDisenios">Modificar</a>
                </th>
            }

            @using (Html.BeginForm("Eliminar", "Administrador", FormMethod.Get, new { @class = "login100-form validate-form p-b-33 p-t-5" }))
            {
                <th scope="col" class="text-danger">
                    <a href="~/Administrador/Eliminar?idDisenios=@item.IdDisenios">Eliminar</a>
                </th>
            }
        </tr>
                
            }
    </tbody>
</table>
<a href="~/Administrador/AgregarDisenio">Agregar diseño</a>

<center>
    <footer class="footer-bs">
        <div class="color">
            &copy; @DateTime.Now.Year</&copy;>
            AJDesign
        </div>
    </footer>
</center>

AJDesign/Views/Shared/VPFooter.cshtml
@{
    ViewBag.Title = "VPFooter";
}

<h2>VPFooter</h2>

<footer class="footer-bs">
    <div class="row">
        <div class="col-md-3 footer-brand animated fadeInLeft">
            <img class="border border-white" id="image-perfil" src="~/Content/Img/logo2.png">
            <p>Programación Web 3 - 1C</p>
            <p>© 2020 PW3, Todos los derechos reservados</p>
        </div>
        <div class="col-md-4 footer-nav animated fadeInUp">
            <h4>Alumnos</h4>
            <div class="col-md-8">
                <ul class="pages">
                    <li><a href="#">Iracheta, Julieta</a></li>
                </ul>
            </div>
        </div>
        <div class="col-md-2 footer-social animated fadeInDown">
            <h4>Grupo</h4>
            <ul>
                <li><a href="https://github.com/IvanNicolasKarlen/App-Covid-19">Grupo 1</a></li>
            </ul>
        </div>
    </div>
</footer>

AJDesign/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title AJDesign</title>
    <link rel="shortcut icon" id="image-perfil" href="/Content/img/favicon.ico">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AJDesign", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Precios", "Precio", "Precios", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Login", "Login", "Administrador", new { area = "" }, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>